theme: jekyll-theme-cayman
title: CNN Magnetism Project
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
table.center {
    margin-left: auto;
    margin-right: auto;
}
